package SI;

public enum Tablas
{
	EDICIONES_UWU,
	JUGADOR_UWU,
	PAREJA_UWU,
	PARTICIPA_UWU,
	ENTRENADOR_UWU,
	PAREJA_ENTRENADA_UWU,
	ESPECTADOR_UWU,
	COMPRA_REALIZA_ENEDICION_UWU,
	COMPRAFINALIZADA_UWU,
	COMPRAPAGADA_UWU,
	ENTRADA_UWU,
	EMITIDAEN_UWU,
	TIENEENTRADAS_UWU,
	ARBITRO_UWU,
	OFERTAS_RECIBE_HECHA_UWU,
	CONTRAOFERTAS_UWU,
	TIENE_UWU,
	PISTAS_UWU,
	PARTIDOS_L_V_TA_TP_UWU,
	EMPRESA_UWU,
	PATROCINA_COLABORA_UWU
}
